solucionamos errores y adaptamos interface

diff --git a/bin/m4bs-display b/bin/m4bs-display
--- a/bin/m4bs-display
+++ b/bin/m4bs-display
@@ -32,15 +32,20 @@ do_log() {
 
 # Comprobamos estado de MEGA
 
-SALIDA=$(mega-whoami 2>&1)
+if [ -f "${CONFIG_FILE}" ]; then
+	source "${CONFIG_FILE}"
+else
+	do_log "[ERROR] El archivo de configuraciones no existe. Vuelva a reinstalar la aplicación"
+	exit 1
+fi
+
+SALIDA=$(cat $CONFIG_FILE | sed "s/PASSWORD=$PASSWORD/PASSWORD=******/gi")
 exitstatus=$?
 if [ $exitstatus = 0 ]; then
-    #echo "$(tput setaf 2)ONLINE"
-    echo "ONLINE"
+    echo $SALIDA
     exit 0
 else
-    #echo "$(tput setaf 1)OFFLINE"
-    echo "OFFLINE"
+    echo "Se ha producido un error y no se pueden mostrar la configuraciones"
     exit 1
 fi
 
